### ISSUE TITLE
Switching between environments eng. Dev, TEST

### ISSUE THREAD

**Issue by vmasule** [christophd/citrus-samples#25]
I am new to citrus and currently evaluating it's suitability for our project. I have created a sample project but I got stuck how I can switch between different environments like Spring-Boot has spring profiles. Is there any example of it switching between environment?

**Comment by NShpakov** [comment]
I am too new to citrus and I also can't understand it.

**Comment by FMAOuroboros** [comment]
Hi!

Just saw this issue here. It would be great if you could open issues and questions concerning citrus in the main project in the future.
https://github.com/christophd/citrus/issues
This is the spot where we're working mainly. It might be the case that issues that are opened here are overseen.

I've moved your question to https://github.com/christophd/citrus/issues/382 for you.

BR,
Sven
