### ISSUE TITLE
citrus and smpp

### ISSUE THREAD

**Issue by NShpakov** [christophd/citrus-samples#27]
Is it possible to implement using citrus support with the smpp protocol?

**Comment by FMAOuroboros** [comment]
Hi!

Just saw this issue here. It would be great if you could open issues and questions concerning citrus in the main project in the future.
https://github.com/christophd/citrus/issues
This is the spot where we're working mainly. It might be the case that issues that are opened here are overseen.

I moved the question to https://github.com/christophd/citrus/issues/383 for you.

BR,
Sven
